apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgen-scaler
  namespace: corbench-{{ .PR_NUMBER }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cortex
  namespace: corbench-{{ .PR_NUMBER }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: avalanche
  namespace: corbench-{{ .PR_NUMBER }}