apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-test-pr-{{ .PR_NUMBER }}
  namespace: corbench-{{ .PR_NUMBER }}
data:
  cortex.yaml: |
    # Configuration for running Cortex in single-process mode.
    # This should not be used in production.  It is only for getting started
    # and development.

    # https://cortexmetrics.io/docs/configuration/configuration-file/#supported-contents-and-default-values-of-the-config-file
    target: all

    # Disable the requirement that every request to Cortex has an
    # X-Scope-OrgID header. `fake` will be substituted in instead.
    auth_enabled: false

    # https://cortexmetrics.io/docs/configuration/configuration-file/#server_config
    server:
      http_listen_port: 9009

      # Configure the server to allow messages up to 100MB.
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      grpc_server_max_concurrent_streams: 1000

    # https://cortexmetrics.io/docs/configuration/configuration-file/#distributor_config
    distributor:
      shard_by_all_labels: true
      pool:
        health_check_ingesters: true

    # https://cortexmetrics.io/docs/configuration/configuration-file/#ingester_client_config
    ingester_client:
      grpc_client_config:
        # Configure the client to allow messages up to 100MB.
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
        grpc_compression: gzip

    # https://cortexmetrics.io/docs/configuration/configuration-file/#ingester_config
    ingester:
      lifecycler:
        # The address to advertise for this ingester.  Will be autodiscovered by
        # looking up address on eth0 or en0; can be specified if this fails.
        # address: 127.0.0.1

        # We want to start immediately and flush on shutdown.
        min_ready_duration: 0s
        final_sleep: 0s
        num_tokens: 512

        # Use an in memory ring store, so we don't need to launch a Consul.
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1

    # https://cortexmetrics.io/docs/configuration/configuration-file/#blocks_storage_config
    blocks_storage:
      backend: filesystem

    # https://cortexmetrics.io/docs/configuration/configuration-file/#compactor_config
    compactor:
      data_dir: /tmp/cortex/compactor
      sharding_ring:
        kvstore:
          store: inmemory

    # https://cortexmetrics.io/docs/configuration/configuration-file/#frontend_worker_config
    frontend_worker:
      match_max_concurrent: true

    # https://cortexmetrics.io/docs/configuration/configuration-file/#ruler_config
    ruler:
      enable_api: true

    # https://cortexmetrics.io/docs/configuration/configuration-file/#ruler_storage_config
    ruler_storage:
      backend: filesystem

    # https://cortexmetrics.io/docs/configuration/configuration-file/#alertmanager_config
    alertmanager:
      external_url: /alertmanager
      enable_api: true
      data_dir: /data/alertmanager

    # https://cortexmetrics.io/docs/configuration/configuration-file/#alertmanager_storage_config
    alertmanager_storage:
      backend: filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-test-pr-{{ .PR_NUMBER }}
  namespace: corbench-{{ .PR_NUMBER }}
  labels:
    app: cortex
    cortex: test-pr-{{ .PR_NUMBER }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex
      cortex: test-pr-{{ .PR_NUMBER }}
  template:
    metadata:
      namespace: corbench-{{ .PR_NUMBER }}
      labels:
        app: cortex
        cortex: test-pr-{{ .PR_NUMBER }}
    spec:
      serviceAccountName: cortex
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cortex
      securityContext:
        runAsUser: 0
      initContainers:
      - name: cortex-builder
        image: docker.io/corbench/cortex-builder:latest
        imagePullPolicy: Always
        env:
        - name: PR_NUMBER
          value: "{{ .PR_NUMBER }}"
        - name: VOLUME_DIR
          value: "/cortex-builder" # same as mountPath
        - name: GITHUB_ORG
          value: "{{ .GITHUB_ORG }}"
        - name: GITHUB_REPO
          value: "{{ .GITHUB_REPO }}"
        volumeMounts:
        - name: cortex-executable
          mountPath: /cortex-builder
      containers:
      - name: cortex
        image: alpine:3.19
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /ready
            port: 9009
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
        command: ["/usr/bin/cortex"]
        args: [
          "-config.file=/etc/cortex/cortex.yaml"
        ]
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            memory: 8Gi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/cortex
        - name: instance-storage
          mountPath: /data
        - name: cortex-executable
          mountPath: /usr/bin
        ports:
        - name: http
          containerPort: 9009
        - name: grpc
          containerPort: 9095
      volumes:
      - name: config-volume
        configMap:
          name: cortex-test-pr-{{ .PR_NUMBER }}
      - name: instance-storage
        emptyDir: {}
      - name: cortex-executable
        emptyDir: {}
      terminationGracePeriodSeconds: 300
      nodeSelector:
        node-name: cortex-{{ .PR_NUMBER }}
---
apiVersion: v1
kind: Service
metadata:
  name: cortex-test-pr-{{ .PR_NUMBER }}
  namespace: corbench-{{ .PR_NUMBER }}
  labels:
    app: cortex
    cortex: test-pr-{{ .PR_NUMBER }}
spec:
  ports:
  - name: http
    port: 9009
    targetPort: http
  - name: grpc
    port: 9095
    targetPort: grpc
  selector:
    app: cortex
    cortex: test-pr-{{ .PR_NUMBER }}